import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const clientDir = path.resolve(__dirname, "..");
const require = createRequire(import.meta.url);

const fonts = [
  ["assistant", ["300", "400", "500", "600", "700"]],
  ["cormorant-garamond", ["400", "500", "600", "700"]],
  ["cormorant-garamond", ["400-italic"]],
  ["frank-ruhl-libre", ["400", "500", "600", "700"]],
  ["caveat", ["500", "600", "700"]],
  ["amatic-sc", ["400", "700"]],
];

function fontsourceDir(pkg) {
  return path.dirname(require.resolve(`@fontsource/${pkg}/package.json`));
}

const publicFontsDir = path.join(clientDir, "public", "fonts");
fs.mkdirSync(publicFontsDir, { recursive: true });

const copied = new Set();

for (const [pkg, weights] of fonts) {
  const filesDir = path.join(fontsourceDir(pkg), "files");
  for (const weight of weights) {
    const cssPath = path.join(fontsourceDir(pkg), `${weight}.css`);
    const css = fs.readFileSync(cssPath, "utf8");
    for (const match of css.matchAll(/url\(\.\/files\/([^)]+)\)/g)) {
      const filename = match[1];
      if (!filename.endsWith(".woff2") || copied.has(filename)) continue;
      fs.copyFileSync(path.join(filesDir, filename), path.join(publicFontsDir, filename));
      copied.add(filename);
    }
  }
}

let out = "/* Generated by scripts/generate-fonts.mjs — do not edit */\n\n";

for (const [pkg, weights] of fonts) {
  for (const weight of weights) {
    const cssPath = path.join(fontsourceDir(pkg), `${weight}.css`);
    const blocks = fs.readFileSync(cssPath, "utf8").split(/(?=\/\* )/);
    for (const block of blocks) {
      if (!block.trim()) continue;
      const match = block.match(/url\(\.\/files\/([^)]+)\)/);
      if (!match || !copied.has(match[1])) continue;
      out +=
        block
          .replace(/font-display:\s*swap/g, "font-display: block")
          .replace(/\.\/files\//g, "/fonts/")
          .replace(/, url\([^)]+\) format\('woff'\)/g, "")
          .trim() + "\n\n";
    }
  }
}

fs.writeFileSync(path.join(clientDir, "src", "fonts.css"), out);
console.log(`Generated src/fonts.css and ${copied.size} files in public/fonts/`);
